# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20191010_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='category',
            field=models.ForeignKey(db_column='cat_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Category'),
        ),
    ]
